services:
  web:
    image: nginx:alpine
    volumes:
      - ./public:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [php]
    labels:
      - "traefik.http.routers.web.rule=Host(`seusite.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"

  php:
    image: php:8.3-fpm-alpine
    volumes:
      - ./public:/var/www/html
      - ./db.php:/var/www/html/db.php            # se estiver fora de public
    environment:
      - TZ=America/Sao_Paulo
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=evo
      - DB_USER=evo
      - DB_PASS=senhaforte

  ws:
    image: php:8.3-cli-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: ["php", "websocket-server.php"]
    restart: unless-stopped
    labels:
      - "traefik.http.services.ws.loadbalancer.server.port=8080"
      - "traefik.http.routers.ws.rule=Host(`ws.seusite.com`)"
      - "traefik.http.routers.ws.entrypoints=websecure"
      - "traefik.http.routers.ws.tls.certresolver=myresolver"

  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: evo
      MYSQL_USER: evo
      MYSQL_PASSWORD: senhaforte
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
