services:
  app:
    build:
      context: .            # <-- era `build: .`
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_NAME: evo
      DB_USER: evo
      DB_PASS: senhaforte
    expose:                 # <-- torna portas visíveis p/ Traefik
      - "80"
      - "8080"
    labels:
      # site normal
      - traefik.http.routers.web.rule=Host(`seusite.com`)
      - traefik.http.routers.web.entrypoints=websecure
      - traefik.http.routers.web.tls.certresolver=myresolver
      - traefik.http.services.web.loadbalancer.server.port=80

      # websocket
      - traefik.http.routers.ws.rule=Host(`ws.seusite.com`)
      - traefik.http.routers.ws.entrypoints=websecure
      - traefik.http.routers.ws.tls.certresolver=myresolver
      - traefik.http.services.ws.loadbalancer.server.port=8080

  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: evo
      MYSQL_USER: evo
      MYSQL_PASSWORD: senhaforte
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
