# Dockerfile.web
FROM php:8.3-fpm-alpine

# libs + extensões
RUN apk add --no-cache nginx bash tzdata \
 && docker-php-ext-install pdo pdo_mysql mysqli

# Composer (somente produção)
RUN php -r "copy('https://getcomposer.org/installer','/tmp/installer.php');" \
 && php /tmp/installer.php --install-dir=/usr/local/bin --filename=composer --quiet \
 && rm /tmp/installer.php

WORKDIR /var/www/html
COPY public/ /var/www/html/
COPY nginx.conf /etc/nginx/http.d/default.conf

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
CMD ["sh","-c","php-fpm -D && exec nginx -g 'daemon off;'"]
